on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Testing on Request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...
